Insert INTO [dbo].[Phase] ([PhaseName], [CreatedBy], [CreatedDate], [SortOrder], [IsActive]) VALUES ('ADVCON' , N'Dataload', GetDate(), 16, 1)
Insert INTO [dbo].[Phase] ([PhaseName], [CreatedBy], [CreatedDate], [SortOrder], [IsActive]) VALUES ('ADVCON (PE2)' , N'Dataload', GetDate(), 12, 1)
Insert INTO [dbo].[Phase] ([PhaseName], [CreatedBy], [CreatedDate], [SortOrder], [IsActive]) VALUES ('ADVCON (PE)' , N'Dataload', GetDate(), 9, 1)
Insert INTO [dbo].[Phase] ([PhaseName], [CreatedBy], [CreatedDate], [SortOrder], [IsActive]) VALUES ('CON' , N'Dataload', GetDate(), 15, 1)
Insert INTO [dbo].[Phase] ([PhaseName], [CreatedBy], [CreatedDate], [SortOrder], [IsActive]) VALUES ('DES' , N'Dataload', GetDate(), 4, 1)
Insert INTO [dbo].[Phase] ([PhaseName], [CreatedBy], [CreatedDate], [SortOrder], [IsActive]) VALUES ('PE2-CON' , N'Dataload', GetDate(), 11, 1)
Insert INTO [dbo].[Phase] ([PhaseName], [CreatedBy], [CreatedDate], [SortOrder], [IsActive]) VALUES ('PE1' , N'Dataload', GetDate(), 8, 1)
Insert INTO [dbo].[Phase] ([PhaseName], [CreatedBy], [CreatedDate], [SortOrder], [IsActive]) VALUES ('PE1/PE2' , N'DataLoad', GetDate(), 6, 1)
Insert INTO [dbo].[Phase] ([PhaseName], [CreatedBy], [CreatedDate], [SortOrder], [IsActive]) VALUES ('EQP' , N'Dataload', GetDate(), 17, 1)
Insert INTO [dbo].[Phase] ([PhaseName], [CreatedBy], [CreatedDate], [SortOrder], [IsActive]) VALUES ('EQP/CON' , N'Dataload', GetDate(), 18, 1)
Insert INTO [dbo].[Phase] ([PhaseName], [CreatedBy], [CreatedDate], [SortOrder], [IsActive]) VALUES ('PE2' , N'Dataload', GetDate(), 10, 1)
Insert INTO [dbo].[Phase] ([PhaseName], [CreatedBy], [CreatedDate], [SortOrder], [IsActive]) VALUES ('HRTP' , N'Dataload', GetDate(), 21, 1)
Insert INTO [dbo].[Phase] ([PhaseName], [CreatedBy], [CreatedDate], [SortOrder], [IsActive]) VALUES ('INSP' , N'Dataload', GetDate(), 19, 1)
Insert INTO [dbo].[Phase] ([PhaseName], [CreatedBy], [CreatedDate], [SortOrder], [IsActive]) VALUES ('OPR' , N'Dataload', GetDate(), 20, 1)
Insert INTO [dbo].[Phase] ([PhaseName], [CreatedBy], [CreatedDate], [SortOrder], [IsActive]) VALUES ('PE-CON' , N'Dataload', GetDate(), 99, 0)
Insert INTO [dbo].[Phase] ([PhaseName], [CreatedBy], [CreatedDate], [SortOrder], [IsActive]) VALUES ('PLN' , N'Dataload', GetDate(), 1, 1)
Insert INTO [dbo].[Phase] ([PhaseName], [CreatedBy], [CreatedDate], [SortOrder], [IsActive]) VALUES ('PLN/EQP/ OPR' , N'Dataload', GetDate(), 3, 1)
Insert INTO [dbo].[Phase] ([PhaseName], [CreatedBy], [CreatedDate], [SortOrder], [IsActive]) VALUES ('PLN/OPR' , N'Dataload', GetDate(), 2, 1)
Insert INTO [dbo].[Phase] ([PhaseName], [CreatedBy], [CreatedDate], [SortOrder], [IsActive]) VALUES ('PE' , N'Dataload', GetDate(), 5, 1)
Insert INTO [dbo].[Phase] ([PhaseName], [CreatedBy], [CreatedDate], [SortOrder], [IsActive]) VALUES ('PE/CON' , N'Dataload', GetDate(), 7, 1)
Insert INTO [dbo].[Phase] ([PhaseName], [CreatedBy], [CreatedDate], [SortOrder], [IsActive]) VALUES ('PREROW' , N'Dataload', GetDate(), 13, 1)
Insert INTO [dbo].[Phase] ([PhaseName], [CreatedBy], [CreatedDate], [SortOrder], [IsActive]) VALUES ('ROW' , N'Dataload', GetDate(), 14, 1)
GO