INSERT INTO [dbo].[ProgramCategory] ([ProgramCategoryName], [Color], [CreatedBy], [CreatedDate], [SortOrder], [IsActive]) VALUES ('Bike/Ped','D02C90','DataLoad' ,GETDATE(), 1 ,1)
INSERT INTO [dbo].[ProgramCategory] ([ProgramCategoryName], [Color], [CreatedBy], [CreatedDate], [SortOrder], [IsActive]) VALUES ('Bridge','902F9B','DataLoad' ,GETDATE(), 2 ,1)
INSERT INTO [dbo].[ProgramCategory] ([ProgramCategoryName], [Color], [CreatedBy], [CreatedDate], [SortOrder], [IsActive]) VALUES ('Capacity','FD437D','DataLoad' ,GETDATE(), 3 ,1)
INSERT INTO [dbo].[ProgramCategory] ([ProgramCategoryName], [Color], [CreatedBy], [CreatedDate], [SortOrder], [IsActive]) VALUES ('Congestion','FDAD7B','DataLoad' ,GETDATE(), 4 ,1)
INSERT INTO [dbo].[ProgramCategory] ([ProgramCategoryName], [Color], [CreatedBy], [CreatedDate], [SortOrder], [IsActive]) VALUES ('Drainage','FAF1D2','DataLoad' ,GETDATE(), 5 ,1)
INSERT INTO [dbo].[ProgramCategory] ([ProgramCategoryName], [Color], [CreatedBy], [CreatedDate], [SortOrder], [IsActive]) VALUES ('Intelligent Transportation Systems','FFE573','DataLoad' ,GETDATE(), 6 ,1)
INSERT INTO [dbo].[ProgramCategory] ([ProgramCategoryName], [Color], [CreatedBy], [CreatedDate], [SortOrder], [IsActive]) VALUES ('Landscaping','8E2E98','DataLoad' ,GETDATE(), 7 ,1)
INSERT INTO [dbo].[ProgramCategory] ([ProgramCategoryName], [Color], [CreatedBy], [CreatedDate], [SortOrder], [IsActive]) VALUES ('O&M','A2D5C6','DataLoad' ,GETDATE(), 8 ,1)
INSERT INTO [dbo].[ProgramCategory] ([ProgramCategoryName], [Color], [CreatedBy], [CreatedDate], [SortOrder], [IsActive]) VALUES ('Other','077B8A','DataLoad' ,GETDATE(), 9 ,1)
INSERT INTO [dbo].[ProgramCategory] ([ProgramCategoryName], [Color], [CreatedBy], [CreatedDate], [SortOrder], [IsActive]) VALUES ('Pavement','039FBE','DataLoad' ,GETDATE(), 10 ,1)
INSERT INTO [dbo].[ProgramCategory] ([ProgramCategoryName], [Color], [CreatedBy], [CreatedDate], [SortOrder], [IsActive]) VALUES ('Retaining Walls','3B4930','DataLoad' ,GETDATE(), 11 ,1)
INSERT INTO [dbo].[ProgramCategory] ([ProgramCategoryName], [Color], [CreatedBy], [CreatedDate], [SortOrder], [IsActive]) VALUES ('Safety','4FD690','DataLoad' ,GETDATE(), 12 ,1)
INSERT INTO [dbo].[ProgramCategory] ([ProgramCategoryName], [Color], [CreatedBy], [CreatedDate], [SortOrder], [IsActive]) VALUES ('Street Light Pole Replacement','35D618','DataLoad' ,GETDATE(), 13 ,1)
INSERT INTO [dbo].[ProgramCategory] ([ProgramCategoryName], [Color], [CreatedBy], [CreatedDate], [SortOrder], [IsActive]) VALUES ('Rockfall','ECC03A','DataLoad' ,GETDATE(), 14 ,1)
INSERT INTO [dbo].[ProgramCategory] ([ProgramCategoryName], [Color], [CreatedBy], [CreatedDate], [SortOrder], [IsActive]) VALUES ('Shoreline','5B2FB2','DataLoad' ,GETDATE(), 15 ,1)
GO
