CREATE DATABASE [HawaiiDOT_MRTP_Dev]
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HawaiiDOT_MRTP_Dev].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [HawaiiDOT_MRTP_Dev] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [HawaiiDOT_MRTP_Dev] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [HawaiiDOT_MRTP_Dev] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [HawaiiDOT_MRTP_Dev] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [HawaiiDOT_MRTP_Dev] SET ARITHABORT OFF 
GO

ALTER DATABASE [HawaiiDOT_MRTP_Dev] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [HawaiiDOT_MRTP_Dev] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [HawaiiDOT_MRTP_Dev] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [HawaiiDOT_MRTP_Dev] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [HawaiiDOT_MRTP_Dev] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [HawaiiDOT_MRTP_Dev] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [HawaiiDOT_MRTP_Dev] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [HawaiiDOT_MRTP_Dev] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [HawaiiDOT_MRTP_Dev] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [HawaiiDOT_MRTP_Dev] SET  DISABLE_BROKER 
GO

ALTER DATABASE [HawaiiDOT_MRTP_Dev] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [HawaiiDOT_MRTP_Dev] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [HawaiiDOT_MRTP_Dev] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [HawaiiDOT_MRTP_Dev] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [HawaiiDOT_MRTP_Dev] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [HawaiiDOT_MRTP_Dev] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [HawaiiDOT_MRTP_Dev] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [HawaiiDOT_MRTP_Dev] SET RECOVERY FULL 
GO

ALTER DATABASE [HawaiiDOT_MRTP_Dev] SET  MULTI_USER 
GO

ALTER DATABASE [HawaiiDOT_MRTP_Dev] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [HawaiiDOT_MRTP_Dev] SET DB_CHAINING OFF 
GO

ALTER DATABASE [HawaiiDOT_MRTP_Dev] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [HawaiiDOT_MRTP_Dev] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [HawaiiDOT_MRTP_Dev] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [HawaiiDOT_MRTP_Dev] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [HawaiiDOT_MRTP_Dev] SET QUERY_STORE = OFF
GO

ALTER DATABASE [HawaiiDOT_MRTP_Dev] SET  READ_WRITE 
GO


